[package]
name = "autosurgeon"
description = "A library for working with data in automerge documents"
version = "0.8.1"
edition = "2021"
authors = ["Alex Good <alex@memoryandthought.me>"]
license = "MIT"
rust-version = "1.65.0"
repository = "https://github.com/automerge/autosurgeon"
readme = "../README.md"

[dependencies]
automerge = { git = "https://github.com/automerge/automerge.git", ref="9f7efc8de69e4e50eba3b95021fda758759b4fb5" }
thiserror = "1.0.37"
smol_str = { version = "^0.1.21" }
autosurgeon-derive = { path = "../autosurgeon-derive", version = "0.7.1" }
similar = "2.2.1"
uuid = { version = "1.2.2", optional = true }

[dev-dependencies]
automerge-test = { git = "https://github.com/automerge/automerge.git", ref="9f7efc8de69e4e50eba3b95021fda758759b4fb5" }

[features]
uuid = ["dep:uuid"]
